# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ahsan2649/Unreal Engine/Unreal Engine 5.3.2
GAMEPROJECTFILE =/home/ahsan2649/Dokumente/Unreal Projects/Weavery/Weavery.uproject

TARGETS = \
	Weavery-Linux-DebugGame  \
	Weavery-Linux-Shipping  \
	Weavery \
	WeaveryEditor-Linux-DebugGame  \
	WeaveryEditor-Linux-Shipping  \
	WeaveryEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend WeaveryEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug WeaveryEditor-Linux-Debug


Weavery-Linux-DebugGame:
	 $(PROJECTBUILD) Weavery Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Weavery-Linux-Shipping:
	 $(PROJECTBUILD) Weavery Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Weavery:
	 $(PROJECTBUILD) Weavery Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

WeaveryEditor-Linux-DebugGame:
	 $(PROJECTBUILD) WeaveryEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

WeaveryEditor-Linux-Shipping:
	 $(PROJECTBUILD) WeaveryEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

WeaveryEditor:
	 $(PROJECTBUILD) WeaveryEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
